name: Haskell CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install stack
      run: |
        curl -sSL https://get.haskellstack.org/ | sh
        
    - name: Setup GHC
      run: |
        stack setup
        
    - name: Setup GHC
      run: |
        stack build
